package wordguess;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.Random;
import java.util.Timer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author rcbgalido
 */
public final class Main extends javax.swing.JFrame {

    private static final int LETTERS_IN_WORD = 7;
    private static final int LINES_IN_WORD_LIST_FILE = 1309;
    private static final int TEN_MILLISECONDS = 10;
    
    private static final String RESOURCE_LOCATION = "resources/";
    private static final String WORD_LIST_FILENAME = "word_list";
    
    private final JButton[] letterButtons;
    private final JTextField[] letterTextFields;
    
    private String randomWord;
    private int guessedLettersCount, triedLettersCount;
    
    private MainTimerTask mainTimerTask;
    
    private ImageIcon titleImage;

    public Main() {
        initComponents();
        setLocationRelativeTo(null); // position frame in the center of the screen
        
        letterButtons = new JButton[]{
            aBTN, bBTN, cBTN, dBTN, eBTN,
            fBTN, gBTN, hBTN, iBTN, jBTN,
            kBTN, lBTN, mBTN, nBTN, oBTN,
            pBTN, qBTN, rBTN, sBTN, tBTN,
            uBTN, vBTN, wBTN, xBTN, yBTN,
            zBTN
        };
        
        letterTextFields = new JTextField[]{
            oneTF, twoTF, threeTF,
            fourTF, fiveTF, sixTF,
            sevenTF
        };
    }
    
    private void clearLetterTextFields() {
        for (JTextField letterTextField : letterTextFields) {
            letterTextField.setText("");
        }
    }
    
    private void resetGuessedLettersCount() {
        guessedLettersCount = 0;
    }
    
    private void resetTriedLettersCount() {
        triedLettersCount = 0;
    }
    
    private void generateRandomWord() {
        InputStream inputStream = getClass().getResourceAsStream(RESOURCE_LOCATION + WORD_LIST_FILENAME);
        Random r = new Random();
        int lineNumber = 1 + r.nextInt(LINES_IN_WORD_LIST_FILE); // 1 line = 1 word

        try {
            BufferedReader reader = new BufferedReader(new InputStreamReader(inputStream));
            for (int a = 1; a < lineNumber; a++) {
                reader.readLine();
            }
            randomWord = reader.readLine().toUpperCase();
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void enableLetterButtons() {
       for (JButton letterButton : letterButtons) {
            letterButton.setEnabled(true);
        } 
    }
    
    private void disableLetterButtons() {
       for (JButton letterButton : letterButtons) {
            letterButton.setEnabled(false);
        } 
    }
    
    private void startTimer() {
        Timer timer = new Timer();
        mainTimerTask = new MainTimerTask();
        timer.scheduleAtFixedRate(mainTimerTask, TEN_MILLISECONDS, TEN_MILLISECONDS);
    }

    private void onClickLetter(String letter) {
        for (int a = 0; a < LETTERS_IN_WORD; a++) {
            if (letter.equals("" + randomWord.charAt(a))) {
                letterTextFields[a].setText(letter);
                guessedLettersCount++;
            }
        }
        triedLettersCount++;

        if (guessedLettersCount == LETTERS_IN_WORD) {
            mainTimerTask.stopTime();
            JOptionPane.showMessageDialog(null, "You got the word in " + mainTimerTask.getTime() 
                    + " seconds (" + triedLettersCount + " tries).", "Message", JOptionPane.INFORMATION_MESSAGE);
            disableLetterButtons();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        aBTN = new javax.swing.JButton();
        bBTN = new javax.swing.JButton();
        cBTN = new javax.swing.JButton();
        dBTN = new javax.swing.JButton();
        eBTN = new javax.swing.JButton();
        fBTN = new javax.swing.JButton();
        gBTN = new javax.swing.JButton();
        hBTN = new javax.swing.JButton();
        iBTN = new javax.swing.JButton();
        jBTN = new javax.swing.JButton();
        kBTN = new javax.swing.JButton();
        lBTN = new javax.swing.JButton();
        mBTN = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        nBTN = new javax.swing.JButton();
        oBTN = new javax.swing.JButton();
        pBTN = new javax.swing.JButton();
        qBTN = new javax.swing.JButton();
        rBTN = new javax.swing.JButton();
        sBTN = new javax.swing.JButton();
        tBTN = new javax.swing.JButton();
        uBTN = new javax.swing.JButton();
        vBTN = new javax.swing.JButton();
        wBTN = new javax.swing.JButton();
        xBTN = new javax.swing.JButton();
        yBTN = new javax.swing.JButton();
        zBTN = new javax.swing.JButton();
        generateBtn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        oneTF = new javax.swing.JTextField();
        twoTF = new javax.swing.JTextField();
        threeTF = new javax.swing.JTextField();
        fourTF = new javax.swing.JTextField();
        fiveTF = new javax.swing.JTextField();
        sixTF = new javax.swing.JTextField();
        sevenTF = new javax.swing.JTextField();
        titleImage=new ImageIcon(getClass().getResource("resources/01_title.png"));
        jLabel2 = new javax.swing.JLabel(titleImage);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("7-Letter Word Guess");
        setResizable(false);

        jPanel4.setBackground(new java.awt.Color(91, 125, 135));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(46, 50, 60), 10));

        jPanel1.setBackground(new java.awt.Color(91, 125, 135));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jPanel2.setBackground(new java.awt.Color(91, 125, 135));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        aBTN.setFont(new java.awt.Font("Arial Unicode MS", 0, 11)); // NOI18N
        aBTN.setText("A");
        aBTN.setEnabled(false);
        aBTN.setFocusable(false);
        aBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letterBTNActionPerformed(evt);
            }
        });
        jPanel2.add(aBTN);

        bBTN.setFont(new java.awt.Font("Arial Unicode MS", 0, 11)); // NOI18N
        bBTN.setText("B");
        bBTN.setEnabled(false);
        bBTN.setFocusable(false);
        bBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letterBTNActionPerformed(evt);
            }
        });
        jPanel2.add(bBTN);

        cBTN.setFont(new java.awt.Font("Arial Unicode MS", 0, 11)); // NOI18N
        cBTN.setText("C");
        cBTN.setEnabled(false);
        cBTN.setFocusable(false);
        cBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letterBTNActionPerformed(evt);
            }
        });
        jPanel2.add(cBTN);

        dBTN.setFont(new java.awt.Font("Arial Unicode MS", 0, 11)); // NOI18N
        dBTN.setText("D");
        dBTN.setEnabled(false);
        dBTN.setFocusable(false);
        dBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letterBTNActionPerformed(evt);
            }
        });
        jPanel2.add(dBTN);

        eBTN.setFont(new java.awt.Font("Arial Unicode MS", 0, 11)); // NOI18N
        eBTN.setText("E");
        eBTN.setEnabled(false);
        eBTN.setFocusable(false);
        eBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letterBTNActionPerformed(evt);
            }
        });
        jPanel2.add(eBTN);

        fBTN.setFont(new java.awt.Font("Arial Unicode MS", 0, 11)); // NOI18N
        fBTN.setText("F");
        fBTN.setEnabled(false);
        fBTN.setFocusable(false);
        fBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letterBTNActionPerformed(evt);
            }
        });
        jPanel2.add(fBTN);

        gBTN.setFont(new java.awt.Font("Arial Unicode MS", 0, 11)); // NOI18N
        gBTN.setText("G");
        gBTN.setEnabled(false);
        gBTN.setFocusable(false);
        gBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letterBTNActionPerformed(evt);
            }
        });
        jPanel2.add(gBTN);

        hBTN.setFont(new java.awt.Font("Arial Unicode MS", 0, 11)); // NOI18N
        hBTN.setText("H");
        hBTN.setEnabled(false);
        hBTN.setFocusable(false);
        hBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letterBTNActionPerformed(evt);
            }
        });
        jPanel2.add(hBTN);

        iBTN.setFont(new java.awt.Font("Arial Unicode MS", 0, 11)); // NOI18N
        iBTN.setText("I");
        iBTN.setEnabled(false);
        iBTN.setFocusable(false);
        iBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letterBTNActionPerformed(evt);
            }
        });
        jPanel2.add(iBTN);

        jBTN.setFont(new java.awt.Font("Arial Unicode MS", 0, 11)); // NOI18N
        jBTN.setText("J");
        jBTN.setEnabled(false);
        jBTN.setFocusable(false);
        jBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letterBTNActionPerformed(evt);
            }
        });
        jPanel2.add(jBTN);

        kBTN.setFont(new java.awt.Font("Arial Unicode MS", 0, 11)); // NOI18N
        kBTN.setText("K");
        kBTN.setEnabled(false);
        kBTN.setFocusable(false);
        kBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letterBTNActionPerformed(evt);
            }
        });
        jPanel2.add(kBTN);

        lBTN.setFont(new java.awt.Font("Arial Unicode MS", 0, 11)); // NOI18N
        lBTN.setText("L");
        lBTN.setEnabled(false);
        lBTN.setFocusable(false);
        lBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letterBTNActionPerformed(evt);
            }
        });
        jPanel2.add(lBTN);

        mBTN.setFont(new java.awt.Font("Arial Unicode MS", 0, 11)); // NOI18N
        mBTN.setText("M");
        mBTN.setEnabled(false);
        mBTN.setFocusable(false);
        mBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letterBTNActionPerformed(evt);
            }
        });
        jPanel2.add(mBTN);

        jPanel3.setBackground(new java.awt.Color(91, 125, 135));
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        nBTN.setFont(new java.awt.Font("Arial Unicode MS", 0, 11)); // NOI18N
        nBTN.setText("N");
        nBTN.setEnabled(false);
        nBTN.setFocusable(false);
        nBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letterBTNActionPerformed(evt);
            }
        });
        jPanel3.add(nBTN);

        oBTN.setFont(new java.awt.Font("Arial Unicode MS", 0, 11)); // NOI18N
        oBTN.setText("O");
        oBTN.setEnabled(false);
        oBTN.setFocusable(false);
        oBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letterBTNActionPerformed(evt);
            }
        });
        jPanel3.add(oBTN);

        pBTN.setFont(new java.awt.Font("Arial Unicode MS", 0, 11)); // NOI18N
        pBTN.setText("P");
        pBTN.setEnabled(false);
        pBTN.setFocusable(false);
        pBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letterBTNActionPerformed(evt);
            }
        });
        jPanel3.add(pBTN);

        qBTN.setFont(new java.awt.Font("Arial Unicode MS", 0, 11)); // NOI18N
        qBTN.setText("Q");
        qBTN.setEnabled(false);
        qBTN.setFocusable(false);
        qBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letterBTNActionPerformed(evt);
            }
        });
        jPanel3.add(qBTN);

        rBTN.setFont(new java.awt.Font("Arial Unicode MS", 0, 11)); // NOI18N
        rBTN.setText("R");
        rBTN.setEnabled(false);
        rBTN.setFocusable(false);
        rBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letterBTNActionPerformed(evt);
            }
        });
        jPanel3.add(rBTN);

        sBTN.setFont(new java.awt.Font("Arial Unicode MS", 0, 11)); // NOI18N
        sBTN.setText("S");
        sBTN.setEnabled(false);
        sBTN.setFocusable(false);
        sBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letterBTNActionPerformed(evt);
            }
        });
        jPanel3.add(sBTN);

        tBTN.setFont(new java.awt.Font("Arial Unicode MS", 0, 11)); // NOI18N
        tBTN.setText("T");
        tBTN.setEnabled(false);
        tBTN.setFocusable(false);
        tBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letterBTNActionPerformed(evt);
            }
        });
        jPanel3.add(tBTN);

        uBTN.setFont(new java.awt.Font("Arial Unicode MS", 0, 11)); // NOI18N
        uBTN.setText("U");
        uBTN.setEnabled(false);
        uBTN.setFocusable(false);
        uBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letterBTNActionPerformed(evt);
            }
        });
        jPanel3.add(uBTN);

        vBTN.setFont(new java.awt.Font("Arial Unicode MS", 0, 11)); // NOI18N
        vBTN.setText("V");
        vBTN.setEnabled(false);
        vBTN.setFocusable(false);
        vBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letterBTNActionPerformed(evt);
            }
        });
        jPanel3.add(vBTN);

        wBTN.setFont(new java.awt.Font("Arial Unicode MS", 0, 11)); // NOI18N
        wBTN.setText("W");
        wBTN.setEnabled(false);
        wBTN.setFocusable(false);
        wBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letterBTNActionPerformed(evt);
            }
        });
        jPanel3.add(wBTN);

        xBTN.setFont(new java.awt.Font("Arial Unicode MS", 0, 11)); // NOI18N
        xBTN.setText("X");
        xBTN.setEnabled(false);
        xBTN.setFocusable(false);
        xBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letterBTNActionPerformed(evt);
            }
        });
        jPanel3.add(xBTN);

        yBTN.setFont(new java.awt.Font("Arial Unicode MS", 0, 11)); // NOI18N
        yBTN.setText("Y");
        yBTN.setEnabled(false);
        yBTN.setFocusable(false);
        yBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letterBTNActionPerformed(evt);
            }
        });
        jPanel3.add(yBTN);

        zBTN.setFont(new java.awt.Font("Arial Unicode MS", 0, 11)); // NOI18N
        zBTN.setText("Z");
        zBTN.setEnabled(false);
        zBTN.setFocusable(false);
        zBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letterBTNActionPerformed(evt);
            }
        });
        jPanel3.add(zBTN);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        generateBtn.setFont(new java.awt.Font("Arial Unicode MS", 0, 11)); // NOI18N
        generateBtn.setText("Generate Word");
        generateBtn.setFocusable(false);
        generateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateBtnActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(91, 125, 135));
        jPanel5.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        oneTF.setEditable(false);
        oneTF.setBackground(new java.awt.Color(204, 204, 204));
        oneTF.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        oneTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        oneTF.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        oneTF.setFocusable(false);
        jPanel5.add(oneTF);

        twoTF.setEditable(false);
        twoTF.setBackground(new java.awt.Color(204, 204, 204));
        twoTF.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        twoTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        twoTF.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        twoTF.setFocusable(false);
        jPanel5.add(twoTF);

        threeTF.setEditable(false);
        threeTF.setBackground(new java.awt.Color(204, 204, 204));
        threeTF.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        threeTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        threeTF.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        threeTF.setFocusable(false);
        jPanel5.add(threeTF);

        fourTF.setEditable(false);
        fourTF.setBackground(new java.awt.Color(204, 204, 204));
        fourTF.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        fourTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fourTF.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fourTF.setFocusable(false);
        jPanel5.add(fourTF);

        fiveTF.setEditable(false);
        fiveTF.setBackground(new java.awt.Color(204, 204, 204));
        fiveTF.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        fiveTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fiveTF.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fiveTF.setFocusable(false);
        jPanel5.add(fiveTF);

        sixTF.setEditable(false);
        sixTF.setBackground(new java.awt.Color(204, 204, 204));
        sixTF.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        sixTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sixTF.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        sixTF.setFocusable(false);
        jPanel5.add(sixTF);

        sevenTF.setEditable(false);
        sevenTF.setBackground(new java.awt.Color(204, 204, 204));
        sevenTF.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        sevenTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sevenTF.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        sevenTF.setFocusable(false);
        jPanel5.add(sevenTF);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(generateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(20, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateBtnActionPerformed
        clearLetterTextFields();
        resetGuessedLettersCount();
        resetTriedLettersCount();
        generateRandomWord();
        enableLetterButtons();
        startTimer();
    }//GEN-LAST:event_generateBtnActionPerformed

    private void letterBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letterBTNActionPerformed
        JButton letterButton = (JButton) evt.getSource();
        letterButton.setEnabled(false);
        onClickLetter(letterButton.getText());
    }//GEN-LAST:event_letterBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aBTN;
    private javax.swing.JButton bBTN;
    private javax.swing.JButton cBTN;
    private javax.swing.JButton dBTN;
    private javax.swing.JButton eBTN;
    private javax.swing.JButton fBTN;
    private javax.swing.JTextField fiveTF;
    private javax.swing.JTextField fourTF;
    private javax.swing.JButton gBTN;
    private javax.swing.JButton generateBtn;
    private javax.swing.JButton hBTN;
    private javax.swing.JButton iBTN;
    private javax.swing.JButton jBTN;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton kBTN;
    private javax.swing.JButton lBTN;
    private javax.swing.JButton mBTN;
    private javax.swing.JButton nBTN;
    private javax.swing.JButton oBTN;
    private javax.swing.JTextField oneTF;
    private javax.swing.JButton pBTN;
    private javax.swing.JButton qBTN;
    private javax.swing.JButton rBTN;
    private javax.swing.JButton sBTN;
    private javax.swing.JTextField sevenTF;
    private javax.swing.JTextField sixTF;
    private javax.swing.JButton tBTN;
    private javax.swing.JTextField threeTF;
    private javax.swing.JTextField twoTF;
    private javax.swing.JButton uBTN;
    private javax.swing.JButton vBTN;
    private javax.swing.JButton wBTN;
    private javax.swing.JButton xBTN;
    private javax.swing.JButton yBTN;
    private javax.swing.JButton zBTN;
    // End of variables declaration//GEN-END:variables
}
